// Code generated by ent, DO NOT EDIT.

package directmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wahab-039/ChatApp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldContainsFold(FieldID, id))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldSenderID, v))
}

// RecipientID applies equality check predicate on the "recipient_id" field. It's identical to RecipientIDEQ.
func RecipientID(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldRecipientID, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldBody, v))
}

// ClientMessageID applies equality check predicate on the "client_message_id" field. It's identical to ClientMessageIDEQ.
func ClientMessageID(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldClientMessageID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDGT applies the GT predicate on the "sender_id" field.
func SenderIDGT(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGT(FieldSenderID, v))
}

// SenderIDGTE applies the GTE predicate on the "sender_id" field.
func SenderIDGTE(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGTE(FieldSenderID, v))
}

// SenderIDLT applies the LT predicate on the "sender_id" field.
func SenderIDLT(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLT(FieldSenderID, v))
}

// SenderIDLTE applies the LTE predicate on the "sender_id" field.
func SenderIDLTE(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLTE(FieldSenderID, v))
}

// SenderIDContains applies the Contains predicate on the "sender_id" field.
func SenderIDContains(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldContains(FieldSenderID, v))
}

// SenderIDHasPrefix applies the HasPrefix predicate on the "sender_id" field.
func SenderIDHasPrefix(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldHasPrefix(FieldSenderID, v))
}

// SenderIDHasSuffix applies the HasSuffix predicate on the "sender_id" field.
func SenderIDHasSuffix(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldHasSuffix(FieldSenderID, v))
}

// SenderIDEqualFold applies the EqualFold predicate on the "sender_id" field.
func SenderIDEqualFold(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEqualFold(FieldSenderID, v))
}

// SenderIDContainsFold applies the ContainsFold predicate on the "sender_id" field.
func SenderIDContainsFold(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldContainsFold(FieldSenderID, v))
}

// RecipientIDEQ applies the EQ predicate on the "recipient_id" field.
func RecipientIDEQ(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldRecipientID, v))
}

// RecipientIDNEQ applies the NEQ predicate on the "recipient_id" field.
func RecipientIDNEQ(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldRecipientID, v))
}

// RecipientIDIn applies the In predicate on the "recipient_id" field.
func RecipientIDIn(vs ...string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldRecipientID, vs...))
}

// RecipientIDNotIn applies the NotIn predicate on the "recipient_id" field.
func RecipientIDNotIn(vs ...string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldRecipientID, vs...))
}

// RecipientIDGT applies the GT predicate on the "recipient_id" field.
func RecipientIDGT(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGT(FieldRecipientID, v))
}

// RecipientIDGTE applies the GTE predicate on the "recipient_id" field.
func RecipientIDGTE(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGTE(FieldRecipientID, v))
}

// RecipientIDLT applies the LT predicate on the "recipient_id" field.
func RecipientIDLT(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLT(FieldRecipientID, v))
}

// RecipientIDLTE applies the LTE predicate on the "recipient_id" field.
func RecipientIDLTE(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLTE(FieldRecipientID, v))
}

// RecipientIDContains applies the Contains predicate on the "recipient_id" field.
func RecipientIDContains(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldContains(FieldRecipientID, v))
}

// RecipientIDHasPrefix applies the HasPrefix predicate on the "recipient_id" field.
func RecipientIDHasPrefix(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldHasPrefix(FieldRecipientID, v))
}

// RecipientIDHasSuffix applies the HasSuffix predicate on the "recipient_id" field.
func RecipientIDHasSuffix(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldHasSuffix(FieldRecipientID, v))
}

// RecipientIDEqualFold applies the EqualFold predicate on the "recipient_id" field.
func RecipientIDEqualFold(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEqualFold(FieldRecipientID, v))
}

// RecipientIDContainsFold applies the ContainsFold predicate on the "recipient_id" field.
func RecipientIDContainsFold(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldContainsFold(FieldRecipientID, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldContainsFold(FieldBody, v))
}

// ClientMessageIDEQ applies the EQ predicate on the "client_message_id" field.
func ClientMessageIDEQ(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldClientMessageID, v))
}

// ClientMessageIDNEQ applies the NEQ predicate on the "client_message_id" field.
func ClientMessageIDNEQ(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldClientMessageID, v))
}

// ClientMessageIDIn applies the In predicate on the "client_message_id" field.
func ClientMessageIDIn(vs ...string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldClientMessageID, vs...))
}

// ClientMessageIDNotIn applies the NotIn predicate on the "client_message_id" field.
func ClientMessageIDNotIn(vs ...string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldClientMessageID, vs...))
}

// ClientMessageIDGT applies the GT predicate on the "client_message_id" field.
func ClientMessageIDGT(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGT(FieldClientMessageID, v))
}

// ClientMessageIDGTE applies the GTE predicate on the "client_message_id" field.
func ClientMessageIDGTE(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGTE(FieldClientMessageID, v))
}

// ClientMessageIDLT applies the LT predicate on the "client_message_id" field.
func ClientMessageIDLT(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLT(FieldClientMessageID, v))
}

// ClientMessageIDLTE applies the LTE predicate on the "client_message_id" field.
func ClientMessageIDLTE(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLTE(FieldClientMessageID, v))
}

// ClientMessageIDContains applies the Contains predicate on the "client_message_id" field.
func ClientMessageIDContains(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldContains(FieldClientMessageID, v))
}

// ClientMessageIDHasPrefix applies the HasPrefix predicate on the "client_message_id" field.
func ClientMessageIDHasPrefix(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldHasPrefix(FieldClientMessageID, v))
}

// ClientMessageIDHasSuffix applies the HasSuffix predicate on the "client_message_id" field.
func ClientMessageIDHasSuffix(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldHasSuffix(FieldClientMessageID, v))
}

// ClientMessageIDEqualFold applies the EqualFold predicate on the "client_message_id" field.
func ClientMessageIDEqualFold(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEqualFold(FieldClientMessageID, v))
}

// ClientMessageIDContainsFold applies the ContainsFold predicate on the "client_message_id" field.
func ClientMessageIDContainsFold(v string) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldContainsFold(FieldClientMessageID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSender applies the HasEdge predicate on the "sender" edge.
func HasSender() predicate.DirectMessage {
	return predicate.DirectMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SenderTable, SenderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSenderWith applies the HasEdge predicate on the "sender" edge with a given conditions (other predicates).
func HasSenderWith(preds ...predicate.User) predicate.DirectMessage {
	return predicate.DirectMessage(func(s *sql.Selector) {
		step := newSenderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecipient applies the HasEdge predicate on the "recipient" edge.
func HasRecipient() predicate.DirectMessage {
	return predicate.DirectMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RecipientTable, RecipientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecipientWith applies the HasEdge predicate on the "recipient" edge with a given conditions (other predicates).
func HasRecipientWith(preds ...predicate.User) predicate.DirectMessage {
	return predicate.DirectMessage(func(s *sql.Selector) {
		step := newRecipientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DirectMessage) predicate.DirectMessage {
	return predicate.DirectMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DirectMessage) predicate.DirectMessage {
	return predicate.DirectMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DirectMessage) predicate.DirectMessage {
	return predicate.DirectMessage(sql.NotPredicates(p))
}
