// Code generated by ent, DO NOT EDIT.

package groupmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wahab-039/ChatApp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContainsFold(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldGroupID, v))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldSenderID, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldBody, v))
}

// ClientMessageID applies equality check predicate on the "client_message_id" field. It's identical to ClientMessageIDEQ.
func ClientMessageID(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldClientMessageID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDContains applies the Contains predicate on the "group_id" field.
func GroupIDContains(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContains(FieldGroupID, v))
}

// GroupIDHasPrefix applies the HasPrefix predicate on the "group_id" field.
func GroupIDHasPrefix(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldHasPrefix(FieldGroupID, v))
}

// GroupIDHasSuffix applies the HasSuffix predicate on the "group_id" field.
func GroupIDHasSuffix(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldHasSuffix(FieldGroupID, v))
}

// GroupIDEqualFold applies the EqualFold predicate on the "group_id" field.
func GroupIDEqualFold(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEqualFold(FieldGroupID, v))
}

// GroupIDContainsFold applies the ContainsFold predicate on the "group_id" field.
func GroupIDContainsFold(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContainsFold(FieldGroupID, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDGT applies the GT predicate on the "sender_id" field.
func SenderIDGT(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldSenderID, v))
}

// SenderIDGTE applies the GTE predicate on the "sender_id" field.
func SenderIDGTE(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldSenderID, v))
}

// SenderIDLT applies the LT predicate on the "sender_id" field.
func SenderIDLT(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldSenderID, v))
}

// SenderIDLTE applies the LTE predicate on the "sender_id" field.
func SenderIDLTE(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldSenderID, v))
}

// SenderIDContains applies the Contains predicate on the "sender_id" field.
func SenderIDContains(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContains(FieldSenderID, v))
}

// SenderIDHasPrefix applies the HasPrefix predicate on the "sender_id" field.
func SenderIDHasPrefix(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldHasPrefix(FieldSenderID, v))
}

// SenderIDHasSuffix applies the HasSuffix predicate on the "sender_id" field.
func SenderIDHasSuffix(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldHasSuffix(FieldSenderID, v))
}

// SenderIDEqualFold applies the EqualFold predicate on the "sender_id" field.
func SenderIDEqualFold(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEqualFold(FieldSenderID, v))
}

// SenderIDContainsFold applies the ContainsFold predicate on the "sender_id" field.
func SenderIDContainsFold(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContainsFold(FieldSenderID, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContainsFold(FieldBody, v))
}

// ClientMessageIDEQ applies the EQ predicate on the "client_message_id" field.
func ClientMessageIDEQ(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldClientMessageID, v))
}

// ClientMessageIDNEQ applies the NEQ predicate on the "client_message_id" field.
func ClientMessageIDNEQ(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldClientMessageID, v))
}

// ClientMessageIDIn applies the In predicate on the "client_message_id" field.
func ClientMessageIDIn(vs ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldClientMessageID, vs...))
}

// ClientMessageIDNotIn applies the NotIn predicate on the "client_message_id" field.
func ClientMessageIDNotIn(vs ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldClientMessageID, vs...))
}

// ClientMessageIDGT applies the GT predicate on the "client_message_id" field.
func ClientMessageIDGT(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldClientMessageID, v))
}

// ClientMessageIDGTE applies the GTE predicate on the "client_message_id" field.
func ClientMessageIDGTE(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldClientMessageID, v))
}

// ClientMessageIDLT applies the LT predicate on the "client_message_id" field.
func ClientMessageIDLT(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldClientMessageID, v))
}

// ClientMessageIDLTE applies the LTE predicate on the "client_message_id" field.
func ClientMessageIDLTE(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldClientMessageID, v))
}

// ClientMessageIDContains applies the Contains predicate on the "client_message_id" field.
func ClientMessageIDContains(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContains(FieldClientMessageID, v))
}

// ClientMessageIDHasPrefix applies the HasPrefix predicate on the "client_message_id" field.
func ClientMessageIDHasPrefix(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldHasPrefix(FieldClientMessageID, v))
}

// ClientMessageIDHasSuffix applies the HasSuffix predicate on the "client_message_id" field.
func ClientMessageIDHasSuffix(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldHasSuffix(FieldClientMessageID, v))
}

// ClientMessageIDEqualFold applies the EqualFold predicate on the "client_message_id" field.
func ClientMessageIDEqualFold(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEqualFold(FieldClientMessageID, v))
}

// ClientMessageIDContainsFold applies the ContainsFold predicate on the "client_message_id" field.
func ClientMessageIDContainsFold(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContainsFold(FieldClientMessageID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupMessage {
	return predicate.GroupMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupMessage {
	return predicate.GroupMessage(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSender applies the HasEdge predicate on the "sender" edge.
func HasSender() predicate.GroupMessage {
	return predicate.GroupMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SenderTable, SenderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSenderWith applies the HasEdge predicate on the "sender" edge with a given conditions (other predicates).
func HasSenderWith(preds ...predicate.User) predicate.GroupMessage {
	return predicate.GroupMessage(func(s *sql.Selector) {
		step := newSenderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupMessage) predicate.GroupMessage {
	return predicate.GroupMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupMessage) predicate.GroupMessage {
	return predicate.GroupMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupMessage) predicate.GroupMessage {
	return predicate.GroupMessage(sql.NotPredicates(p))
}
