package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// GroupMessage holds the schema definition for the GroupMessage entity.
type GroupMessage struct {
	ent.Schema
}

// Fields of the GroupMessage.
func (GroupMessage) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			NotEmpty().
			Immutable(),

		// group_id and sender_id are FKs wired to edges below
		field.String("group_id").
			NotEmpty(),

		field.String("sender_id").
			NotEmpty(),

		// body maps to models.GroupMessage.Body
		field.String("body").
			NotEmpty(),

		// client_message_id: deduplication ID generated by the client
		// Unique per sender — enforced by index below
		field.String("client_message_id").
			MaxLen(128).
			NotEmpty(),

		field.Time("created_at").
			Default(time.Now).
			Immutable(), // Group messages are never edited
	}
}

// Edges of the GroupMessage.
func (GroupMessage) Edges() []ent.Edge {
	return []ent.Edge{
		// The group this message belongs to.
		// Ref("messages") links back to Group.Edges → edge.To("messages")
		// Field("group_id") wires the FK column to this edge
		edge.From("group", Group.Type).
			Ref("messages").
			Field("group_id").
			Unique(). // Many messages → One group
			Required(),

		// The user who sent this message.
		// Ref("sent_group_messages") links back to User.Edges → edge.To("sent_group_messages")
		edge.From("sender", User.Type).
			Ref("sent_group_messages").
			Field("sender_id").
			Unique(). // Many messages → One sender
			Required(),
	}
}

// Indexes of the GroupMessage.
func (GroupMessage) Indexes() []ent.Index {
	return []ent.Index{
		// Matches DB: UNIQUE (sender_id, client_message_id)
		// Prevents duplicate messages from the same client
		index.Fields("sender_id", "client_message_id").Unique(),

		// Matches DB: CREATE INDEX group_messages_group_created_at_idx
		// ON group_messages(group_id, created_at DESC)
		// Used for paginated listing of messages within a group
		index.Fields("group_id", "created_at"),

		// Matches DB: CREATE INDEX group_messages_sender_idx ON group_messages(sender_id)
		index.Fields("sender_id"),
	}
}

// Annotations tell Ent to use the exact existing table name.
func (GroupMessage) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "group_messages"},
	}
}
