// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DirectMessagesColumns holds the columns for the "direct_messages" table.
	DirectMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "body", Type: field.TypeString},
		{Name: "client_message_id", Type: field.TypeString, Size: 128},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "sender_id", Type: field.TypeString},
		{Name: "recipient_id", Type: field.TypeString},
	}
	// DirectMessagesTable holds the schema information for the "direct_messages" table.
	DirectMessagesTable = &schema.Table{
		Name:       "direct_messages",
		Columns:    DirectMessagesColumns,
		PrimaryKey: []*schema.Column{DirectMessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "direct_messages_users_sent_messages",
				Columns:    []*schema.Column{DirectMessagesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "direct_messages_users_received_messages",
				Columns:    []*schema.Column{DirectMessagesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "directmessage_sender_id_client_message_id",
				Unique:  true,
				Columns: []*schema.Column{DirectMessagesColumns[4], DirectMessagesColumns[2]},
			},
			{
				Name:    "directmessage_sender_id_recipient_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{DirectMessagesColumns[4], DirectMessagesColumns[5], DirectMessagesColumns[3]},
			},
			{
				Name:    "directmessage_recipient_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{DirectMessagesColumns[5], DirectMessagesColumns[3]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "groups_users_created_groups",
				Columns:    []*schema.Column{GroupsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "group_created_by",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[4]},
			},
		},
	}
	// GroupMembersColumns holds the columns for the "group_members" table.
	GroupMembersColumns = []*schema.Column{
		{Name: "group_id", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "member"}, Default: "member"},
		{Name: "joined_at", Type: field.TypeTime},
		{Name: "group_memberships", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// GroupMembersTable holds the schema information for the "group_members" table.
	GroupMembersTable = &schema.Table{
		Name:       "group_members",
		Columns:    GroupMembersColumns,
		PrimaryKey: []*schema.Column{GroupMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_members_groups_memberships",
				Columns:    []*schema.Column{GroupMembersColumns[3]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "group_members_users_memberships",
				Columns:    []*schema.Column{GroupMembersColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "groupmember_group_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{GroupMembersColumns[0], GroupMembersColumns[4]},
			},
			{
				Name:    "groupmember_user_id",
				Unique:  false,
				Columns: []*schema.Column{GroupMembersColumns[4]},
			},
			{
				Name:    "groupmember_group_id",
				Unique:  false,
				Columns: []*schema.Column{GroupMembersColumns[0]},
			},
		},
	}
	// GroupMessagesColumns holds the columns for the "group_messages" table.
	GroupMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "body", Type: field.TypeString},
		{Name: "client_message_id", Type: field.TypeString, Size: 128},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "group_id", Type: field.TypeString},
		{Name: "sender_id", Type: field.TypeString},
	}
	// GroupMessagesTable holds the schema information for the "group_messages" table.
	GroupMessagesTable = &schema.Table{
		Name:       "group_messages",
		Columns:    GroupMessagesColumns,
		PrimaryKey: []*schema.Column{GroupMessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_messages_groups_messages",
				Columns:    []*schema.Column{GroupMessagesColumns[4]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "group_messages_users_sent_group_messages",
				Columns:    []*schema.Column{GroupMessagesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "groupmessage_sender_id_client_message_id",
				Unique:  true,
				Columns: []*schema.Column{GroupMessagesColumns[5], GroupMessagesColumns[2]},
			},
			{
				Name:    "groupmessage_group_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{GroupMessagesColumns[4], GroupMessagesColumns[3]},
			},
			{
				Name:    "groupmessage_sender_id",
				Unique:  false,
				Columns: []*schema.Column{GroupMessagesColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Size: 30},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DirectMessagesTable,
		GroupsTable,
		GroupMembersTable,
		GroupMessagesTable,
		UsersTable,
	}
)

func init() {
	DirectMessagesTable.ForeignKeys[0].RefTable = UsersTable
	DirectMessagesTable.ForeignKeys[1].RefTable = UsersTable
	DirectMessagesTable.Annotation = &entsql.Annotation{
		Table: "direct_messages",
	}
	GroupsTable.ForeignKeys[0].RefTable = UsersTable
	GroupsTable.Annotation = &entsql.Annotation{
		Table: "groups",
	}
	GroupMembersTable.ForeignKeys[0].RefTable = GroupsTable
	GroupMembersTable.ForeignKeys[1].RefTable = UsersTable
	GroupMembersTable.Annotation = &entsql.Annotation{
		Table: "group_members",
	}
	GroupMessagesTable.ForeignKeys[0].RefTable = GroupsTable
	GroupMessagesTable.ForeignKeys[1].RefTable = UsersTable
	GroupMessagesTable.Annotation = &entsql.Annotation{
		Table: "group_messages",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
