// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wahab-039/ChatApp/ent/directmessage"
	"github.com/Wahab-039/ChatApp/ent/user"
)

// DirectMessageCreate is the builder for creating a DirectMessage entity.
type DirectMessageCreate struct {
	config
	mutation *DirectMessageMutation
	hooks    []Hook
}

// SetSenderID sets the "sender_id" field.
func (_c *DirectMessageCreate) SetSenderID(v string) *DirectMessageCreate {
	_c.mutation.SetSenderID(v)
	return _c
}

// SetRecipientID sets the "recipient_id" field.
func (_c *DirectMessageCreate) SetRecipientID(v string) *DirectMessageCreate {
	_c.mutation.SetRecipientID(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *DirectMessageCreate) SetBody(v string) *DirectMessageCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetClientMessageID sets the "client_message_id" field.
func (_c *DirectMessageCreate) SetClientMessageID(v string) *DirectMessageCreate {
	_c.mutation.SetClientMessageID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DirectMessageCreate) SetCreatedAt(v time.Time) *DirectMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DirectMessageCreate) SetNillableCreatedAt(v *time.Time) *DirectMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DirectMessageCreate) SetID(v string) *DirectMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSender sets the "sender" edge to the User entity.
func (_c *DirectMessageCreate) SetSender(v *User) *DirectMessageCreate {
	return _c.SetSenderID(v.ID)
}

// SetRecipient sets the "recipient" edge to the User entity.
func (_c *DirectMessageCreate) SetRecipient(v *User) *DirectMessageCreate {
	return _c.SetRecipientID(v.ID)
}

// Mutation returns the DirectMessageMutation object of the builder.
func (_c *DirectMessageCreate) Mutation() *DirectMessageMutation {
	return _c.mutation
}

// Save creates the DirectMessage in the database.
func (_c *DirectMessageCreate) Save(ctx context.Context) (*DirectMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DirectMessageCreate) SaveX(ctx context.Context) *DirectMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DirectMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DirectMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DirectMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := directmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DirectMessageCreate) check() error {
	if _, ok := _c.mutation.SenderID(); !ok {
		return &ValidationError{Name: "sender_id", err: errors.New(`ent: missing required field "DirectMessage.sender_id"`)}
	}
	if v, ok := _c.mutation.SenderID(); ok {
		if err := directmessage.SenderIDValidator(v); err != nil {
			return &ValidationError{Name: "sender_id", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.sender_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecipientID(); !ok {
		return &ValidationError{Name: "recipient_id", err: errors.New(`ent: missing required field "DirectMessage.recipient_id"`)}
	}
	if v, ok := _c.mutation.RecipientID(); ok {
		if err := directmessage.RecipientIDValidator(v); err != nil {
			return &ValidationError{Name: "recipient_id", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.recipient_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "DirectMessage.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := directmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientMessageID(); !ok {
		return &ValidationError{Name: "client_message_id", err: errors.New(`ent: missing required field "DirectMessage.client_message_id"`)}
	}
	if v, ok := _c.mutation.ClientMessageID(); ok {
		if err := directmessage.ClientMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "client_message_id", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.client_message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DirectMessage.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := directmessage.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.id": %w`, err)}
		}
	}
	if len(_c.mutation.SenderIDs()) == 0 {
		return &ValidationError{Name: "sender", err: errors.New(`ent: missing required edge "DirectMessage.sender"`)}
	}
	if len(_c.mutation.RecipientIDs()) == 0 {
		return &ValidationError{Name: "recipient", err: errors.New(`ent: missing required edge "DirectMessage.recipient"`)}
	}
	return nil
}

func (_c *DirectMessageCreate) sqlSave(ctx context.Context) (*DirectMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DirectMessage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DirectMessageCreate) createSpec() (*DirectMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &DirectMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(directmessage.Table, sqlgraph.NewFieldSpec(directmessage.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(directmessage.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.ClientMessageID(); ok {
		_spec.SetField(directmessage.FieldClientMessageID, field.TypeString, value)
		_node.ClientMessageID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(directmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directmessage.SenderTable,
			Columns: []string{directmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SenderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecipientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directmessage.RecipientTable,
			Columns: []string{directmessage.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RecipientID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DirectMessageCreateBulk is the builder for creating many DirectMessage entities in bulk.
type DirectMessageCreateBulk struct {
	config
	err      error
	builders []*DirectMessageCreate
}

// Save creates the DirectMessage entities in the database.
func (_c *DirectMessageCreateBulk) Save(ctx context.Context) ([]*DirectMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DirectMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DirectMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DirectMessageCreateBulk) SaveX(ctx context.Context) []*DirectMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DirectMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DirectMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
