// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wahab-039/ChatApp/ent/directmessage"
	"github.com/Wahab-039/ChatApp/ent/user"
)

// DirectMessage is the model entity for the DirectMessage schema.
type DirectMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// SenderID holds the value of the "sender_id" field.
	SenderID string `json:"sender_id,omitempty"`
	// RecipientID holds the value of the "recipient_id" field.
	RecipientID string `json:"recipient_id,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// ClientMessageID holds the value of the "client_message_id" field.
	ClientMessageID string `json:"client_message_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DirectMessageQuery when eager-loading is set.
	Edges        DirectMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DirectMessageEdges holds the relations/edges for other nodes in the graph.
type DirectMessageEdges struct {
	// Sender holds the value of the sender edge.
	Sender *User `json:"sender,omitempty"`
	// Recipient holds the value of the recipient edge.
	Recipient *User `json:"recipient,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SenderOrErr returns the Sender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DirectMessageEdges) SenderOrErr() (*User, error) {
	if e.Sender != nil {
		return e.Sender, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "sender"}
}

// RecipientOrErr returns the Recipient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DirectMessageEdges) RecipientOrErr() (*User, error) {
	if e.Recipient != nil {
		return e.Recipient, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "recipient"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DirectMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case directmessage.FieldID, directmessage.FieldSenderID, directmessage.FieldRecipientID, directmessage.FieldBody, directmessage.FieldClientMessageID:
			values[i] = new(sql.NullString)
		case directmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DirectMessage fields.
func (_m *DirectMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case directmessage.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case directmessage.FieldSenderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_id", values[i])
			} else if value.Valid {
				_m.SenderID = value.String
			}
		case directmessage.FieldRecipientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_id", values[i])
			} else if value.Valid {
				_m.RecipientID = value.String
			}
		case directmessage.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case directmessage.FieldClientMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_message_id", values[i])
			} else if value.Valid {
				_m.ClientMessageID = value.String
			}
		case directmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DirectMessage.
// This includes values selected through modifiers, order, etc.
func (_m *DirectMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySender queries the "sender" edge of the DirectMessage entity.
func (_m *DirectMessage) QuerySender() *UserQuery {
	return NewDirectMessageClient(_m.config).QuerySender(_m)
}

// QueryRecipient queries the "recipient" edge of the DirectMessage entity.
func (_m *DirectMessage) QueryRecipient() *UserQuery {
	return NewDirectMessageClient(_m.config).QueryRecipient(_m)
}

// Update returns a builder for updating this DirectMessage.
// Note that you need to call DirectMessage.Unwrap() before calling this method if this DirectMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DirectMessage) Update() *DirectMessageUpdateOne {
	return NewDirectMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DirectMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DirectMessage) Unwrap() *DirectMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DirectMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DirectMessage) String() string {
	var builder strings.Builder
	builder.WriteString("DirectMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("sender_id=")
	builder.WriteString(_m.SenderID)
	builder.WriteString(", ")
	builder.WriteString("recipient_id=")
	builder.WriteString(_m.RecipientID)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("client_message_id=")
	builder.WriteString(_m.ClientMessageID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DirectMessages is a parsable slice of DirectMessage.
type DirectMessages []*DirectMessage
