// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wahab-039/ChatApp/ent/directmessage"
	"github.com/Wahab-039/ChatApp/ent/predicate"
	"github.com/Wahab-039/ChatApp/ent/user"
)

// DirectMessageUpdate is the builder for updating DirectMessage entities.
type DirectMessageUpdate struct {
	config
	hooks    []Hook
	mutation *DirectMessageMutation
}

// Where appends a list predicates to the DirectMessageUpdate builder.
func (_u *DirectMessageUpdate) Where(ps ...predicate.DirectMessage) *DirectMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *DirectMessageUpdate) SetSenderID(v string) *DirectMessageUpdate {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *DirectMessageUpdate) SetNillableSenderID(v *string) *DirectMessageUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetRecipientID sets the "recipient_id" field.
func (_u *DirectMessageUpdate) SetRecipientID(v string) *DirectMessageUpdate {
	_u.mutation.SetRecipientID(v)
	return _u
}

// SetNillableRecipientID sets the "recipient_id" field if the given value is not nil.
func (_u *DirectMessageUpdate) SetNillableRecipientID(v *string) *DirectMessageUpdate {
	if v != nil {
		_u.SetRecipientID(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *DirectMessageUpdate) SetBody(v string) *DirectMessageUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *DirectMessageUpdate) SetNillableBody(v *string) *DirectMessageUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetClientMessageID sets the "client_message_id" field.
func (_u *DirectMessageUpdate) SetClientMessageID(v string) *DirectMessageUpdate {
	_u.mutation.SetClientMessageID(v)
	return _u
}

// SetNillableClientMessageID sets the "client_message_id" field if the given value is not nil.
func (_u *DirectMessageUpdate) SetNillableClientMessageID(v *string) *DirectMessageUpdate {
	if v != nil {
		_u.SetClientMessageID(*v)
	}
	return _u
}

// SetSender sets the "sender" edge to the User entity.
func (_u *DirectMessageUpdate) SetSender(v *User) *DirectMessageUpdate {
	return _u.SetSenderID(v.ID)
}

// SetRecipient sets the "recipient" edge to the User entity.
func (_u *DirectMessageUpdate) SetRecipient(v *User) *DirectMessageUpdate {
	return _u.SetRecipientID(v.ID)
}

// Mutation returns the DirectMessageMutation object of the builder.
func (_u *DirectMessageUpdate) Mutation() *DirectMessageMutation {
	return _u.mutation
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *DirectMessageUpdate) ClearSender() *DirectMessageUpdate {
	_u.mutation.ClearSender()
	return _u
}

// ClearRecipient clears the "recipient" edge to the User entity.
func (_u *DirectMessageUpdate) ClearRecipient() *DirectMessageUpdate {
	_u.mutation.ClearRecipient()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DirectMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DirectMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DirectMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DirectMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DirectMessageUpdate) check() error {
	if v, ok := _u.mutation.SenderID(); ok {
		if err := directmessage.SenderIDValidator(v); err != nil {
			return &ValidationError{Name: "sender_id", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.sender_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientID(); ok {
		if err := directmessage.RecipientIDValidator(v); err != nil {
			return &ValidationError{Name: "recipient_id", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.recipient_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := directmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientMessageID(); ok {
		if err := directmessage.ClientMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "client_message_id", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.client_message_id": %w`, err)}
		}
	}
	if _u.mutation.SenderCleared() && len(_u.mutation.SenderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DirectMessage.sender"`)
	}
	if _u.mutation.RecipientCleared() && len(_u.mutation.RecipientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DirectMessage.recipient"`)
	}
	return nil
}

func (_u *DirectMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(directmessage.Table, directmessage.Columns, sqlgraph.NewFieldSpec(directmessage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(directmessage.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientMessageID(); ok {
		_spec.SetField(directmessage.FieldClientMessageID, field.TypeString, value)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directmessage.SenderTable,
			Columns: []string{directmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directmessage.SenderTable,
			Columns: []string{directmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecipientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directmessage.RecipientTable,
			Columns: []string{directmessage.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directmessage.RecipientTable,
			Columns: []string{directmessage.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{directmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DirectMessageUpdateOne is the builder for updating a single DirectMessage entity.
type DirectMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DirectMessageMutation
}

// SetSenderID sets the "sender_id" field.
func (_u *DirectMessageUpdateOne) SetSenderID(v string) *DirectMessageUpdateOne {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *DirectMessageUpdateOne) SetNillableSenderID(v *string) *DirectMessageUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetRecipientID sets the "recipient_id" field.
func (_u *DirectMessageUpdateOne) SetRecipientID(v string) *DirectMessageUpdateOne {
	_u.mutation.SetRecipientID(v)
	return _u
}

// SetNillableRecipientID sets the "recipient_id" field if the given value is not nil.
func (_u *DirectMessageUpdateOne) SetNillableRecipientID(v *string) *DirectMessageUpdateOne {
	if v != nil {
		_u.SetRecipientID(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *DirectMessageUpdateOne) SetBody(v string) *DirectMessageUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *DirectMessageUpdateOne) SetNillableBody(v *string) *DirectMessageUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetClientMessageID sets the "client_message_id" field.
func (_u *DirectMessageUpdateOne) SetClientMessageID(v string) *DirectMessageUpdateOne {
	_u.mutation.SetClientMessageID(v)
	return _u
}

// SetNillableClientMessageID sets the "client_message_id" field if the given value is not nil.
func (_u *DirectMessageUpdateOne) SetNillableClientMessageID(v *string) *DirectMessageUpdateOne {
	if v != nil {
		_u.SetClientMessageID(*v)
	}
	return _u
}

// SetSender sets the "sender" edge to the User entity.
func (_u *DirectMessageUpdateOne) SetSender(v *User) *DirectMessageUpdateOne {
	return _u.SetSenderID(v.ID)
}

// SetRecipient sets the "recipient" edge to the User entity.
func (_u *DirectMessageUpdateOne) SetRecipient(v *User) *DirectMessageUpdateOne {
	return _u.SetRecipientID(v.ID)
}

// Mutation returns the DirectMessageMutation object of the builder.
func (_u *DirectMessageUpdateOne) Mutation() *DirectMessageMutation {
	return _u.mutation
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *DirectMessageUpdateOne) ClearSender() *DirectMessageUpdateOne {
	_u.mutation.ClearSender()
	return _u
}

// ClearRecipient clears the "recipient" edge to the User entity.
func (_u *DirectMessageUpdateOne) ClearRecipient() *DirectMessageUpdateOne {
	_u.mutation.ClearRecipient()
	return _u
}

// Where appends a list predicates to the DirectMessageUpdate builder.
func (_u *DirectMessageUpdateOne) Where(ps ...predicate.DirectMessage) *DirectMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DirectMessageUpdateOne) Select(field string, fields ...string) *DirectMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DirectMessage entity.
func (_u *DirectMessageUpdateOne) Save(ctx context.Context) (*DirectMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DirectMessageUpdateOne) SaveX(ctx context.Context) *DirectMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DirectMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DirectMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DirectMessageUpdateOne) check() error {
	if v, ok := _u.mutation.SenderID(); ok {
		if err := directmessage.SenderIDValidator(v); err != nil {
			return &ValidationError{Name: "sender_id", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.sender_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientID(); ok {
		if err := directmessage.RecipientIDValidator(v); err != nil {
			return &ValidationError{Name: "recipient_id", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.recipient_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := directmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientMessageID(); ok {
		if err := directmessage.ClientMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "client_message_id", err: fmt.Errorf(`ent: validator failed for field "DirectMessage.client_message_id": %w`, err)}
		}
	}
	if _u.mutation.SenderCleared() && len(_u.mutation.SenderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DirectMessage.sender"`)
	}
	if _u.mutation.RecipientCleared() && len(_u.mutation.RecipientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DirectMessage.recipient"`)
	}
	return nil
}

func (_u *DirectMessageUpdateOne) sqlSave(ctx context.Context) (_node *DirectMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(directmessage.Table, directmessage.Columns, sqlgraph.NewFieldSpec(directmessage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DirectMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, directmessage.FieldID)
		for _, f := range fields {
			if !directmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != directmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(directmessage.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientMessageID(); ok {
		_spec.SetField(directmessage.FieldClientMessageID, field.TypeString, value)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directmessage.SenderTable,
			Columns: []string{directmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directmessage.SenderTable,
			Columns: []string{directmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecipientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directmessage.RecipientTable,
			Columns: []string{directmessage.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directmessage.RecipientTable,
			Columns: []string{directmessage.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DirectMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{directmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
