// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wahab-039/ChatApp/ent/group"
	"github.com/Wahab-039/ChatApp/ent/groupmessage"
	"github.com/Wahab-039/ChatApp/ent/user"
)

// GroupMessageCreate is the builder for creating a GroupMessage entity.
type GroupMessageCreate struct {
	config
	mutation *GroupMessageMutation
	hooks    []Hook
}

// SetGroupID sets the "group_id" field.
func (_c *GroupMessageCreate) SetGroupID(v string) *GroupMessageCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetSenderID sets the "sender_id" field.
func (_c *GroupMessageCreate) SetSenderID(v string) *GroupMessageCreate {
	_c.mutation.SetSenderID(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *GroupMessageCreate) SetBody(v string) *GroupMessageCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetClientMessageID sets the "client_message_id" field.
func (_c *GroupMessageCreate) SetClientMessageID(v string) *GroupMessageCreate {
	_c.mutation.SetClientMessageID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupMessageCreate) SetCreatedAt(v time.Time) *GroupMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupMessageCreate) SetNillableCreatedAt(v *time.Time) *GroupMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GroupMessageCreate) SetID(v string) *GroupMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupMessageCreate) SetGroup(v *Group) *GroupMessageCreate {
	return _c.SetGroupID(v.ID)
}

// SetSender sets the "sender" edge to the User entity.
func (_c *GroupMessageCreate) SetSender(v *User) *GroupMessageCreate {
	return _c.SetSenderID(v.ID)
}

// Mutation returns the GroupMessageMutation object of the builder.
func (_c *GroupMessageCreate) Mutation() *GroupMessageMutation {
	return _c.mutation
}

// Save creates the GroupMessage in the database.
func (_c *GroupMessageCreate) Save(ctx context.Context) (*GroupMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupMessageCreate) SaveX(ctx context.Context) *GroupMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupMessageCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupMessage.group_id"`)}
	}
	if v, ok := _c.mutation.GroupID(); ok {
		if err := groupmessage.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.group_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SenderID(); !ok {
		return &ValidationError{Name: "sender_id", err: errors.New(`ent: missing required field "GroupMessage.sender_id"`)}
	}
	if v, ok := _c.mutation.SenderID(); ok {
		if err := groupmessage.SenderIDValidator(v); err != nil {
			return &ValidationError{Name: "sender_id", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.sender_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "GroupMessage.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := groupmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientMessageID(); !ok {
		return &ValidationError{Name: "client_message_id", err: errors.New(`ent: missing required field "GroupMessage.client_message_id"`)}
	}
	if v, ok := _c.mutation.ClientMessageID(); ok {
		if err := groupmessage.ClientMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "client_message_id", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.client_message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupMessage.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := groupmessage.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.id": %w`, err)}
		}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupMessage.group"`)}
	}
	if len(_c.mutation.SenderIDs()) == 0 {
		return &ValidationError{Name: "sender", err: errors.New(`ent: missing required edge "GroupMessage.sender"`)}
	}
	return nil
}

func (_c *GroupMessageCreate) sqlSave(ctx context.Context) (*GroupMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected GroupMessage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupMessageCreate) createSpec() (*GroupMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupmessage.Table, sqlgraph.NewFieldSpec(groupmessage.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(groupmessage.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.ClientMessageID(); ok {
		_spec.SetField(groupmessage.FieldClientMessageID, field.TypeString, value)
		_node.ClientMessageID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmessage.GroupTable,
			Columns: []string{groupmessage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmessage.SenderTable,
			Columns: []string{groupmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SenderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GroupMessageCreateBulk is the builder for creating many GroupMessage entities in bulk.
type GroupMessageCreateBulk struct {
	config
	err      error
	builders []*GroupMessageCreate
}

// Save creates the GroupMessage entities in the database.
func (_c *GroupMessageCreateBulk) Save(ctx context.Context) ([]*GroupMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupMessageCreateBulk) SaveX(ctx context.Context) []*GroupMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
