// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wahab-039/ChatApp/ent/group"
	"github.com/Wahab-039/ChatApp/ent/groupmessage"
	"github.com/Wahab-039/ChatApp/ent/predicate"
	"github.com/Wahab-039/ChatApp/ent/user"
)

// GroupMessageUpdate is the builder for updating GroupMessage entities.
type GroupMessageUpdate struct {
	config
	hooks    []Hook
	mutation *GroupMessageMutation
}

// Where appends a list predicates to the GroupMessageUpdate builder.
func (_u *GroupMessageUpdate) Where(ps ...predicate.GroupMessage) *GroupMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupMessageUpdate) SetGroupID(v string) *GroupMessageUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupMessageUpdate) SetNillableGroupID(v *string) *GroupMessageUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *GroupMessageUpdate) SetSenderID(v string) *GroupMessageUpdate {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *GroupMessageUpdate) SetNillableSenderID(v *string) *GroupMessageUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *GroupMessageUpdate) SetBody(v string) *GroupMessageUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *GroupMessageUpdate) SetNillableBody(v *string) *GroupMessageUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetClientMessageID sets the "client_message_id" field.
func (_u *GroupMessageUpdate) SetClientMessageID(v string) *GroupMessageUpdate {
	_u.mutation.SetClientMessageID(v)
	return _u
}

// SetNillableClientMessageID sets the "client_message_id" field if the given value is not nil.
func (_u *GroupMessageUpdate) SetNillableClientMessageID(v *string) *GroupMessageUpdate {
	if v != nil {
		_u.SetClientMessageID(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupMessageUpdate) SetGroup(v *Group) *GroupMessageUpdate {
	return _u.SetGroupID(v.ID)
}

// SetSender sets the "sender" edge to the User entity.
func (_u *GroupMessageUpdate) SetSender(v *User) *GroupMessageUpdate {
	return _u.SetSenderID(v.ID)
}

// Mutation returns the GroupMessageMutation object of the builder.
func (_u *GroupMessageUpdate) Mutation() *GroupMessageMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupMessageUpdate) ClearGroup() *GroupMessageUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *GroupMessageUpdate) ClearSender() *GroupMessageUpdate {
	_u.mutation.ClearSender()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupMessageUpdate) check() error {
	if v, ok := _u.mutation.GroupID(); ok {
		if err := groupmessage.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.group_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderID(); ok {
		if err := groupmessage.SenderIDValidator(v); err != nil {
			return &ValidationError{Name: "sender_id", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.sender_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := groupmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientMessageID(); ok {
		if err := groupmessage.ClientMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "client_message_id", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.client_message_id": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupMessage.group"`)
	}
	if _u.mutation.SenderCleared() && len(_u.mutation.SenderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupMessage.sender"`)
	}
	return nil
}

func (_u *GroupMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupmessage.Table, groupmessage.Columns, sqlgraph.NewFieldSpec(groupmessage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(groupmessage.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientMessageID(); ok {
		_spec.SetField(groupmessage.FieldClientMessageID, field.TypeString, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmessage.GroupTable,
			Columns: []string{groupmessage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmessage.GroupTable,
			Columns: []string{groupmessage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmessage.SenderTable,
			Columns: []string{groupmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmessage.SenderTable,
			Columns: []string{groupmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupMessageUpdateOne is the builder for updating a single GroupMessage entity.
type GroupMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupMessageMutation
}

// SetGroupID sets the "group_id" field.
func (_u *GroupMessageUpdateOne) SetGroupID(v string) *GroupMessageUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupMessageUpdateOne) SetNillableGroupID(v *string) *GroupMessageUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *GroupMessageUpdateOne) SetSenderID(v string) *GroupMessageUpdateOne {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *GroupMessageUpdateOne) SetNillableSenderID(v *string) *GroupMessageUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *GroupMessageUpdateOne) SetBody(v string) *GroupMessageUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *GroupMessageUpdateOne) SetNillableBody(v *string) *GroupMessageUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetClientMessageID sets the "client_message_id" field.
func (_u *GroupMessageUpdateOne) SetClientMessageID(v string) *GroupMessageUpdateOne {
	_u.mutation.SetClientMessageID(v)
	return _u
}

// SetNillableClientMessageID sets the "client_message_id" field if the given value is not nil.
func (_u *GroupMessageUpdateOne) SetNillableClientMessageID(v *string) *GroupMessageUpdateOne {
	if v != nil {
		_u.SetClientMessageID(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupMessageUpdateOne) SetGroup(v *Group) *GroupMessageUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetSender sets the "sender" edge to the User entity.
func (_u *GroupMessageUpdateOne) SetSender(v *User) *GroupMessageUpdateOne {
	return _u.SetSenderID(v.ID)
}

// Mutation returns the GroupMessageMutation object of the builder.
func (_u *GroupMessageUpdateOne) Mutation() *GroupMessageMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupMessageUpdateOne) ClearGroup() *GroupMessageUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *GroupMessageUpdateOne) ClearSender() *GroupMessageUpdateOne {
	_u.mutation.ClearSender()
	return _u
}

// Where appends a list predicates to the GroupMessageUpdate builder.
func (_u *GroupMessageUpdateOne) Where(ps ...predicate.GroupMessage) *GroupMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupMessageUpdateOne) Select(field string, fields ...string) *GroupMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupMessage entity.
func (_u *GroupMessageUpdateOne) Save(ctx context.Context) (*GroupMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupMessageUpdateOne) SaveX(ctx context.Context) *GroupMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupMessageUpdateOne) check() error {
	if v, ok := _u.mutation.GroupID(); ok {
		if err := groupmessage.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.group_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderID(); ok {
		if err := groupmessage.SenderIDValidator(v); err != nil {
			return &ValidationError{Name: "sender_id", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.sender_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := groupmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientMessageID(); ok {
		if err := groupmessage.ClientMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "client_message_id", err: fmt.Errorf(`ent: validator failed for field "GroupMessage.client_message_id": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupMessage.group"`)
	}
	if _u.mutation.SenderCleared() && len(_u.mutation.SenderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupMessage.sender"`)
	}
	return nil
}

func (_u *GroupMessageUpdateOne) sqlSave(ctx context.Context) (_node *GroupMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupmessage.Table, groupmessage.Columns, sqlgraph.NewFieldSpec(groupmessage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupmessage.FieldID)
		for _, f := range fields {
			if !groupmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(groupmessage.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientMessageID(); ok {
		_spec.SetField(groupmessage.FieldClientMessageID, field.TypeString, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmessage.GroupTable,
			Columns: []string{groupmessage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmessage.GroupTable,
			Columns: []string{groupmessage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmessage.SenderTable,
			Columns: []string{groupmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmessage.SenderTable,
			Columns: []string{groupmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
