// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Wahab-039/ChatApp/ent/directmessage"
	"github.com/Wahab-039/ChatApp/ent/group"
	"github.com/Wahab-039/ChatApp/ent/groupmember"
	"github.com/Wahab-039/ChatApp/ent/groupmessage"
	"github.com/Wahab-039/ChatApp/ent/schema"
	"github.com/Wahab-039/ChatApp/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	directmessageFields := schema.DirectMessage{}.Fields()
	_ = directmessageFields
	// directmessageDescSenderID is the schema descriptor for sender_id field.
	directmessageDescSenderID := directmessageFields[1].Descriptor()
	// directmessage.SenderIDValidator is a validator for the "sender_id" field. It is called by the builders before save.
	directmessage.SenderIDValidator = directmessageDescSenderID.Validators[0].(func(string) error)
	// directmessageDescRecipientID is the schema descriptor for recipient_id field.
	directmessageDescRecipientID := directmessageFields[2].Descriptor()
	// directmessage.RecipientIDValidator is a validator for the "recipient_id" field. It is called by the builders before save.
	directmessage.RecipientIDValidator = directmessageDescRecipientID.Validators[0].(func(string) error)
	// directmessageDescBody is the schema descriptor for body field.
	directmessageDescBody := directmessageFields[3].Descriptor()
	// directmessage.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	directmessage.BodyValidator = directmessageDescBody.Validators[0].(func(string) error)
	// directmessageDescClientMessageID is the schema descriptor for client_message_id field.
	directmessageDescClientMessageID := directmessageFields[4].Descriptor()
	// directmessage.ClientMessageIDValidator is a validator for the "client_message_id" field. It is called by the builders before save.
	directmessage.ClientMessageIDValidator = func() func(string) error {
		validators := directmessageDescClientMessageID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_message_id string) error {
			for _, fn := range fns {
				if err := fn(client_message_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// directmessageDescCreatedAt is the schema descriptor for created_at field.
	directmessageDescCreatedAt := directmessageFields[5].Descriptor()
	// directmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	directmessage.DefaultCreatedAt = directmessageDescCreatedAt.Default.(func() time.Time)
	// directmessageDescID is the schema descriptor for id field.
	directmessageDescID := directmessageFields[0].Descriptor()
	// directmessage.IDValidator is a validator for the "id" field. It is called by the builders before save.
	directmessage.IDValidator = directmessageDescID.Validators[0].(func(string) error)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[1].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = func() func(string) error {
		validators := groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescCreatedBy is the schema descriptor for created_by field.
	groupDescCreatedBy := groupFields[2].Descriptor()
	// group.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	group.CreatedByValidator = groupDescCreatedBy.Validators[0].(func(string) error)
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupFields[3].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupFields[4].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// groupDescID is the schema descriptor for id field.
	groupDescID := groupFields[0].Descriptor()
	// group.IDValidator is a validator for the "id" field. It is called by the builders before save.
	group.IDValidator = groupDescID.Validators[0].(func(string) error)
	groupmemberFields := schema.GroupMember{}.Fields()
	_ = groupmemberFields
	// groupmemberDescUserID is the schema descriptor for user_id field.
	groupmemberDescUserID := groupmemberFields[1].Descriptor()
	// groupmember.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	groupmember.UserIDValidator = groupmemberDescUserID.Validators[0].(func(string) error)
	// groupmemberDescJoinedAt is the schema descriptor for joined_at field.
	groupmemberDescJoinedAt := groupmemberFields[3].Descriptor()
	// groupmember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	groupmember.DefaultJoinedAt = groupmemberDescJoinedAt.Default.(func() time.Time)
	// groupmemberDescID is the schema descriptor for id field.
	groupmemberDescID := groupmemberFields[0].Descriptor()
	// groupmember.IDValidator is a validator for the "id" field. It is called by the builders before save.
	groupmember.IDValidator = groupmemberDescID.Validators[0].(func(string) error)
	groupmessageFields := schema.GroupMessage{}.Fields()
	_ = groupmessageFields
	// groupmessageDescGroupID is the schema descriptor for group_id field.
	groupmessageDescGroupID := groupmessageFields[1].Descriptor()
	// groupmessage.GroupIDValidator is a validator for the "group_id" field. It is called by the builders before save.
	groupmessage.GroupIDValidator = groupmessageDescGroupID.Validators[0].(func(string) error)
	// groupmessageDescSenderID is the schema descriptor for sender_id field.
	groupmessageDescSenderID := groupmessageFields[2].Descriptor()
	// groupmessage.SenderIDValidator is a validator for the "sender_id" field. It is called by the builders before save.
	groupmessage.SenderIDValidator = groupmessageDescSenderID.Validators[0].(func(string) error)
	// groupmessageDescBody is the schema descriptor for body field.
	groupmessageDescBody := groupmessageFields[3].Descriptor()
	// groupmessage.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	groupmessage.BodyValidator = groupmessageDescBody.Validators[0].(func(string) error)
	// groupmessageDescClientMessageID is the schema descriptor for client_message_id field.
	groupmessageDescClientMessageID := groupmessageFields[4].Descriptor()
	// groupmessage.ClientMessageIDValidator is a validator for the "client_message_id" field. It is called by the builders before save.
	groupmessage.ClientMessageIDValidator = func() func(string) error {
		validators := groupmessageDescClientMessageID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_message_id string) error {
			for _, fn := range fns {
				if err := fn(client_message_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupmessageDescCreatedAt is the schema descriptor for created_at field.
	groupmessageDescCreatedAt := groupmessageFields[5].Descriptor()
	// groupmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	groupmessage.DefaultCreatedAt = groupmessageDescCreatedAt.Default.(func() time.Time)
	// groupmessageDescID is the schema descriptor for id field.
	groupmessageDescID := groupmessageFields[0].Descriptor()
	// groupmessage.IDValidator is a validator for the "id" field. It is called by the builders before save.
	groupmessage.IDValidator = groupmessageDescID.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
