apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-data-pvc
  namespace: chatapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
