// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSentMessages holds the string denoting the sent_messages edge name in mutations.
	EdgeSentMessages = "sent_messages"
	// EdgeReceivedMessages holds the string denoting the received_messages edge name in mutations.
	EdgeReceivedMessages = "received_messages"
	// EdgeCreatedGroups holds the string denoting the created_groups edge name in mutations.
	EdgeCreatedGroups = "created_groups"
	// EdgeMemberships holds the string denoting the memberships edge name in mutations.
	EdgeMemberships = "memberships"
	// EdgeSentGroupMessages holds the string denoting the sent_group_messages edge name in mutations.
	EdgeSentGroupMessages = "sent_group_messages"
	// GroupMemberFieldID holds the string denoting the ID field of the GroupMember.
	GroupMemberFieldID = "group_id"
	// Table holds the table name of the user in the database.
	Table = "users"
	// SentMessagesTable is the table that holds the sent_messages relation/edge.
	SentMessagesTable = "direct_messages"
	// SentMessagesInverseTable is the table name for the DirectMessage entity.
	// It exists in this package in order to avoid circular dependency with the "directmessage" package.
	SentMessagesInverseTable = "direct_messages"
	// SentMessagesColumn is the table column denoting the sent_messages relation/edge.
	SentMessagesColumn = "sender_id"
	// ReceivedMessagesTable is the table that holds the received_messages relation/edge.
	ReceivedMessagesTable = "direct_messages"
	// ReceivedMessagesInverseTable is the table name for the DirectMessage entity.
	// It exists in this package in order to avoid circular dependency with the "directmessage" package.
	ReceivedMessagesInverseTable = "direct_messages"
	// ReceivedMessagesColumn is the table column denoting the received_messages relation/edge.
	ReceivedMessagesColumn = "recipient_id"
	// CreatedGroupsTable is the table that holds the created_groups relation/edge.
	CreatedGroupsTable = "groups"
	// CreatedGroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	CreatedGroupsInverseTable = "groups"
	// CreatedGroupsColumn is the table column denoting the created_groups relation/edge.
	CreatedGroupsColumn = "created_by"
	// MembershipsTable is the table that holds the memberships relation/edge.
	MembershipsTable = "group_members"
	// MembershipsInverseTable is the table name for the GroupMember entity.
	// It exists in this package in order to avoid circular dependency with the "groupmember" package.
	MembershipsInverseTable = "group_members"
	// MembershipsColumn is the table column denoting the memberships relation/edge.
	MembershipsColumn = "user_id"
	// SentGroupMessagesTable is the table that holds the sent_group_messages relation/edge.
	SentGroupMessagesTable = "group_messages"
	// SentGroupMessagesInverseTable is the table name for the GroupMessage entity.
	// It exists in this package in order to avoid circular dependency with the "groupmessage" package.
	SentGroupMessagesInverseTable = "group_messages"
	// SentGroupMessagesColumn is the table column denoting the sent_group_messages relation/edge.
	SentGroupMessagesColumn = "sender_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPasswordHash,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySentMessagesCount orders the results by sent_messages count.
func BySentMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSentMessagesStep(), opts...)
	}
}

// BySentMessages orders the results by sent_messages terms.
func BySentMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSentMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReceivedMessagesCount orders the results by received_messages count.
func ByReceivedMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReceivedMessagesStep(), opts...)
	}
}

// ByReceivedMessages orders the results by received_messages terms.
func ByReceivedMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReceivedMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCreatedGroupsCount orders the results by created_groups count.
func ByCreatedGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCreatedGroupsStep(), opts...)
	}
}

// ByCreatedGroups orders the results by created_groups terms.
func ByCreatedGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMembershipsCount orders the results by memberships count.
func ByMembershipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMembershipsStep(), opts...)
	}
}

// ByMemberships orders the results by memberships terms.
func ByMemberships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMembershipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySentGroupMessagesCount orders the results by sent_group_messages count.
func BySentGroupMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSentGroupMessagesStep(), opts...)
	}
}

// BySentGroupMessages orders the results by sent_group_messages terms.
func BySentGroupMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSentGroupMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSentMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SentMessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SentMessagesTable, SentMessagesColumn),
	)
}
func newReceivedMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReceivedMessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReceivedMessagesTable, ReceivedMessagesColumn),
	)
}
func newCreatedGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedGroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CreatedGroupsTable, CreatedGroupsColumn),
	)
}
func newMembershipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembershipsInverseTable, GroupMemberFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MembershipsTable, MembershipsColumn),
	)
}
func newSentGroupMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SentGroupMessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SentGroupMessagesTable, SentGroupMessagesColumn),
	)
}
