// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DirectMessage is the predicate function for directmessage builders.
type DirectMessage func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupMember is the predicate function for groupmember builders.
type GroupMember func(*sql.Selector)

// GroupMessage is the predicate function for groupmessage builders.
type GroupMessage func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
